"""empty message

Revision ID: 0d67a444474e
Revises: efe9cf8277cb
Create Date: 2020-04-04 08:42:17.338413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d67a444474e'
down_revision = 'efe9cf8277cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'institution_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('institution_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'class', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###
