"""empty message

Revision ID: 0ee9c04826b9
Revises: c53522110aac
Create Date: 2020-04-04 01:51:43.644615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee9c04826b9'
down_revision = 'c53522110aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('photo', sa.String(length=250), nullable=True))
    op.add_column('relative', sa.Column('photo', sa.String(length=250), nullable=True))
    op.add_column('student', sa.Column('photo', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'photo')
    op.drop_column('relative', 'photo')
    op.drop_column('manager', 'photo')
    # ### end Alembic commands ###
