"""empty message

Revision ID: 11c67f2316a9
Revises: c572dd53ed7c
Create Date: 2020-04-04 15:16:54.504033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c67f2316a9'
down_revision = 'c572dd53ed7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'class', ['class_id'], ['id'])
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
