"""empty message

Revision ID: 2f7bb2af7a98
Revises: 5768851640fb
Create Date: 2020-04-05 14:03:56.525870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bb2af7a98'
down_revision = '5768851640fb'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('event', sa.Column('date', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
