"""empty message

Revision ID: 35db552856f9
Revises: 5feea90e7dff
Create Date: 2020-04-05 13:55:06.172383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35db552856f9'
down_revision = '5feea90e7dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("oi")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("vlw")
    # ### end Alembic commands ###
