"""empty message

Revision ID: 3dffda275d52
Revises: fdb6dd9ab631
Create Date: 2020-04-04 10:55:02.190261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dffda275d52'
down_revision = 'fdb6dd9ab631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.drop_column('grade', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('student_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'grade', 'student', ['student_id'], ['id'])
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
