"""empty message

Revision ID: 52fa0f0c9e21
Revises: cb31b29ef8a9
Create Date: 2020-04-05 13:33:25.390431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fa0f0c9e21'
down_revision = 'cb31b29ef8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("oi")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("vlw")
    # ### end Alembic commands ###
