"""empty message

Revision ID: 5feea90e7dff
Revises: 25fed774b505
Create Date: 2020-04-05 13:54:19.971883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5feea90e7dff'
down_revision = '25fed774b505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.String(length=250), nullable=False, default="10/04/2020"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
