"""empty message

Revision ID: 90989a053317
Revises: 52fa0f0c9e21
Create Date: 2020-04-05 13:51:07.978064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90989a053317'
down_revision = '52fa0f0c9e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("oi")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("vlw")
    # ### end Alembic commands ###
