"""empty message

Revision ID: ed990d1d55cf
Revises: c04e45e6fb95
Create Date: 2020-04-04 11:31:05.961023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed990d1d55cf'
down_revision = 'c04e45e6fb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'class', ['class_id'], ['id'])
    op.alter_column('class', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
